### ISSUE TITLE
Backfill AzureGovServiceTags

### ISSUE THREAD

**Issue by noskcajflor** [jelledruyts/AzureServiceTags#1]
Hello, 

I was curious if you maintained a backup of any of the service tag files posted here: 

https://azservicetags.azurewebsites.net/

I noticed that Microsoft didn't have a repository of the past files and was hoping to get a backfill for all the files uploaded in December.

**Comment by jelledruyts** [comment]
Ah, no, I'm afraid not, I only cache the latest version so I can't go back in time. Sorry!

**Comment by noskcajflor** [comment]
No worries, thanks for the quick reply!
